const questions = [
  "What embarrasses you the most andor what's been your most embarrassing moment?",
  "Who do you look up to the most, and what qualities do you love about that person?",
  "What's your biggest fear?",
  "What's your love language?",
  "How do you like to be comforted when you're sad or upset?",
  "What's your all-time favorite memory?",
  "Who was the last person to make you cry and why?",
  "Where do you hope to be five years from now? Ten? Fifteen?",
  "When have you felt the most proud?",
  "When have you felt the most challenged?",
  "Have you ever been bullied?",
  "Do you have any regrets? If so, what are they?",
  "Out of all your family members, who are you closest to?",
  "What's one thing most people don’t know about you?",
  "What do you think happens when we die?",
  "Do you want to have kids one day? How many?",
  "What's your earliest childhood memory?",
  "If you could change one thing about yourself, what would it be?",
  "Do you believe in soulmates?",
  "When you can't sleep, what keeps you up at night?",
  "What has your hardest goodbye in life been so far?",
  "What's the worst date you’ve ever been on?",
  "What's a talent you wish you had or that you're working on?",
  "Which celeb would you want as your other BFF and why?",
  "What do you do when no one else is around?",
  "What's the best present you ever received? Who gave it to you and why was it so special?",
  "What's the last thing you watched on Netflix?",
  "What do you consider the ultimate comfort food?",
  "If you could only have three things on your life bucket list, what would they be?",
  "Would you rather be an expert at one thing, or pretty good at many things?",
  "What's your favorite thing you own and why?",
  "Have you ever had your fortune told?",
  "Would you rather order in or eat out?",
  "What was the first movie you remember seeing in theaters?",
  "What's your favorite TikTok video?",
  "What's been your most questionable haircut andor fashion moment?",
  "If money was no object, what would you buy?",
  "When was the moment in your life you laughed the hardest?",
  "Where do you want to travel the most?",
  "If you could only eat one thing for the rest of your life, what would it be?",
  "What book has impacted you the most?",
  "What's your favorite movie romance? commercial?",
  "What are the qualities that attract you most in a love interest?",
  "You just won $10,000 — what are you going to do with the money?",
  "What's the luckiest thing that's ever happened to you?",
  "What's your favorite way to exercise?",
  "Do you like roller coasters?",
  "What is your most hated chore and why?",
  "What's your favorite holiday and why?",
  "If you were going to get some ink, what would you choose and why?",
  "If you had three wishes, what would you wish for?",
  "If you had to choose only one, would you pick a dog or a cat?",
  "Do you believe in aliens?",
  "If you were President, what's the first thing you would work to change in this country?",
  "If you had to live in another time period, what would you choose?",
  "What foreign language(s) would you want to master and why?",
  "What's your all-time favorite dessert?",
  "Do you believe in ghosts?",
  "What's your survival plan during a zombie apocalypse?",
  "If you had to create an alter ego for yourself, who would it be and what would you name them?",
  "What's your No",
  "Have you ever been on a blind date?",
  "What was your AIM screen name, or your first email address?",
  "What's your favorite piece of random trivia?",
  "What was your first concert?",
  "Which decade, in your opinion, had the best fashion trends?",
  "If a song played every time you entered a room, what would it be?",
  "What's your skincare routine?",
  "Did you ever go to summer camp?",
  "When's the last time you got to really experience nature?",
  "Do you feel that you're young at heart, or an old soul?",
  "What does your name mean, and why was it given to you?",
  "What's an unexpected movie that makes you cry?",
  "What flavor of ice cream best represents your personality?",
  "What's the one snack you can’t live without?",
  "What's the first place you’d go to in the mall?",
  "What's the scariest or most thrilling roller coaster you’ve ever been on?",
  "What's the last song you listened to?",
  "Which item in your closet is your favorite?",
  "What is your key to a cozy evening in?",
  "What's the last video game you played?",
  "What's the last thing TikTok convinced you to buy?",
  "What's the last lie you told?",
  "Who was your very first crush?",
  "What's the best compliment you've ever received?",
  "What do you consider your best physical feature?",
  "What are the top three things that stress you out?",
  "What are the top three ways you deal with stress?",
  "When was the last time you were jealous and why?",
  "Do you believe in monogamy?",
  "If you choose to get married one day, what would your dream proposal scenario be?",
  "What would your dream home look like?",
  "When's the last time you felt inspired to create something?",
  "How did your parents meet?",
  "Who's been your favorite teacher?",
  "What are your favorite childrens’ names?",
  "What did you dream about last night?",
  "What do you think you’ll be like in old age?",
  "What's the worst decision you’ve ever made?",
  "What's something you’d consider unforgivable?",
  "What's the most loved you’ve ever felt?",
  "Have you ever experienced a “friendship breakup”? What did it teach you?",
  "Who was your first friend, and are they still in your life?",
  "Would you ever consider being in a long-distance relationship?",
  "What do you think the best way to resolve conflict is?",
  "Do you feel that you have a healthy relationship with social media?",
  "Is there a time when I made you feel particularly well supported?",
  "How can I be a better friend to you?",
  "What does friendship mean to you?",
  "What qualities do you look for in a best friend?",
  "What's the most important thing I should know about you?",
  "What are your pronouns?",
  "What would be your perfect day? Plan it out from waking up to bedtime",
  "What's your zodiac sign?",
  "What's your Enneagram type?",
  "On vacation, are you the relax-by-the-pool type or a get-up-and-go adventurer?",
  "Do you consider yourself religious or spiritual?",
  "What college major are you thinking of choosing and why?",
  "If you could only listen to one singer or band for the rest of your life, who would you choose?",
  "What's your go-to dish when you have to make dinner?",
  "Are you a superstitious person?",
  "What's your favorite board game to play?",
  "Who's the best movie villain?",
  "Who's your favorite follow on TikTok? On Instagram?",
  "Did you have an imaginary friend growing up?",
  "If you had to describe yourself in only three words, what would you choose? What words do you think your friends would choose to describe you?",
  "Do you have any phobias?",
  "What are your top three biggest pet peeves?",
  "What's your favorite color and what's your least favorite color?",
  "What would your dream vacay consist of?",
  "Are you competitive?",
  "What's a tough experience that you learned and grew from?",
  "What's your relationship with your parents like?",
  "Do you most often follow your heart or your head?",
  "What's the most unexpected or unusual thing on your bucket list?",
  "What was your last romantic relationship like?",
  "What's a value you're unwilling to compromise on?",
  "What's your absolute dream job?",
  "If you could have a superpower, what would you choose?",
  "What TV show do you turn on when you just want to zone out and feel better?",
  "What was the last movie you watched in a theater?",
  "If you could time travel, where would you go?",
  "What do you usually have for breakfast?",
  "What's your favorite plant or flower?",
  "What's your favorite season and why?",
  "Who always makes you laugh?",
  "What do you think your best quality is?",
  "What is your definition of success?",
  "What's your most-watched movie?",
  "Do you have any hidden talents?",
  "What's the best thing you’ve dressed up as for Halloween?",
  "Would you rather live by the ocean or in the mountains?",
  "What's the longest trip you’ve taken?",
  "Are you a right brain or left brain person?",
  "What is your most-used emoji?",
  "What's a bad habit you're trying to break?",
  "What's the scariest movie you’ve ever seen?",
  "Are you a morning person or a night owl?",
  "Do you like to recharge alone or around other people?",
  "What's the best museum you’ve ever been to?",
  "When can we hang out again?",
  "Which fictional character do you most relate to?",
  "What would your ideal friend hangout include?",
  "What food do you absolutely hate?",
  "Do you believe in your horoscope?",
  "What's your most used emoji?"
];
const maxQuestions = questions.length


randNum = maxQuestions => Math.floor(Math.random() * maxQuestions);

function newQuestion() {
    document.getElementById("qOnScreen").innerHTML = questions[randNum(questions.length)]
}
