const questions = [
  "How do you determine your development period? Why do you consider it is reasonable?",
"Why do you propose transfer plate? Is it common?",
"Why do you adopt these comparables even there is an obvious difference between reference unit size and compabale unit size?",
"Why don't you select adopted comparables for pair comp analysis of quantum adjustment?",
"Why do you adopt comparables located on such low floor level when compared with reference unit? This gives rise to high floor adjustment so still valid?",
"What do you mean actual floor level?",
"How do you perform development scale adjustment?",
"How do you arrive at the net consideration? What cash rebates/discounts are deducted? Show me detailed working of calculation",
"Why do you adopt different cost unit rate for apartment and balcony and utility platform? Is it fair to adopt different rates?",
"How do you perform your view adjustment? Reasonable for such high %?",
"Do you know the resumption of Golf Club",
"Why do you assume town planning approval was obtained even though the question states that there is no approval yet?",
"Do you assume approval was obtained or it is expected to get approval?",
"Why do you raise the headroom level to 4.5m for office? Do you think it is marketable?",
"Do you think there will be higher rental value for office with headroom above 4m when compared with office with headroom below 4m?",
"Share with me your insights in HKIS Valuation Standard 2020",
"Is there any difference when you work in private sector and in government when reviewing the Valuation Standards? Shared with me your experience",
"Is Valuation Standards mandatory or just a guideline? any difference?",
"Do you know anything about Cap 626",
"If you work in Valuation Section of LandsD and your friend raises an appeal, what will you do?",
"Can you tell us what your selection criteria for the GDV comparables for both the 'Before' and 'After' scenarios?",
"Why would the hypothetical developments for the 'Before' and 'After' in terms of flat size (no. of beds) are different, given that you have just said the market prefers small flat size in recent 2‐3 years?",
"Why the flat size for your 'Before' scenario is not even bigger in order to achieve a higher efficiency ratio?",
"Did you consider special units e.g. duplex units in your 'Before' scenario?",
"You have made a lot of adjustments to your 'Before' GDV comparables. However, the total adjustments were about 20‐30%, don’t you think it is a very substantial adjustment? Such adjustment has lowered that transaction price of each comparable all the way down, I may think that you are purposely discounting the 'Before' value so substantially in order to charge a higher land premium on behalf of the Government. What capacity were you sitting at when you are working on this assessment?",
"Currently you are using a technique i.e. 'Before' and 'After' to assess the premium. What is the logic / rationale behind this premium assessment method?",
"You are adopting 6% and 2% of total GFA for 'After' and 'Before' assessments for the plant room area respectively. Is it fair to adopt such a small scale of plant room for the 'Before' scenario? Is it technically feasible?",
"Referring to the construction costs for apartment, why would you use exactly the same unit rate cost for your 'After' and 'Before' scenarios which would have totally different building form and type of foundation etc.?",
"Do you know the difference between plot ratio GFA and construction floor area, in terms of construction costs?",
"You have 11 covered CPS in your 'After' scenario and made an assumption of 40 sqm for each CPS. Do you think it is too little?",
"For your car park comparable, it only got 3 nos. CPS provided on G/F but your hypothetical scenario got 6 nos., is your site big enough to incorporate all the CPS?",
"I see the overall adjusted unit rate of comparables for your 'After' typical apartment were about $230K‐$250K /sqm only, but you have adopted an overall average unit rate of $270K /sqm for your residual assessment. Why?",
"a) Why do you have saleable area and effective area? What are their differences?",
"How did you arrive at the adjustment ratio for EA from SA?",
"Each of your 'After' comparable has a total GFA of about 4,000 sqm, which is similar to your subject 'After' development. Why would you adopt a 10% adjustment on development scale?",
"In your past experience, you are more familiar with the residential market. How about the office market?",
"Where are you working now? What post?",
"What do you understand about “investment value”?",
"Can you tell us about estate agency practices?",
"Do you know the differences between “basic rent” and “turnover rent” for leasing rental?",
"What do you understand about “professional ethics”, “professional conduct” and “professional integrity”? Any differences between these three terminologies?",
"Which do you is more important? No matter which party you are working for, say in Government, Developer etc?",
"Have you considered alternative proposals for your development?",
"What is your basis of area?",
"What are some considerations of your adjustments for comparables?",
"see that you have four developments for car parking spaces. Some of them are the “Four Little Dragon”. Have you considered the differences between these developments and your subject (single‐block development)?",
"Do you rely on just one development for the CPS comparables?",
"Have you considered duplex units provided that there is some open view for your developments?",
"How do you come up with your development period.",
"How do you come up with your 7% professional fee?",
"How to value a shop with a 10‐year tenancy?",
"What is the yield of shops around your subject site?",
"Is it gross yield or net yield?",
"Do you notice that there is a recent government sale site in Central?",
"Follow‐up to Q16): As you said, there is a large difference in the 1st bid and 2nd bid. Which do you think is the market value?",
"Do you know what is “Smart City”? What are some opportunities and threats for surveyors?",
"How to value a co‐living space?",
"What is the name of the approach?",
"Do you know how many cases have TPB approved the redevelopment of this kind of developments? As you are evaluating the redevelopment value, would you reconsider?",
"Your uncle asks you to value a site of your company at a lower value so that he can buy the site. What would you do?",
"Size adjustment, how do you derive this %? Why 1% per 5m²?",
"Why smaller unit size fetch a higher unit rate? Even for this luxurious development",
"Your site is a sloped site, any implication on land value?",
"Your assessed land value is 30% lower than the tender price, why? If you get another chance to assess the land value again, would you adjust your value higher?",
"Why not allow larger unit size, with 2 units per floor? (my hypo is 3 units per floor)",
"Any special unit?",
"Why need 3 levels of basement? Why not 2 levels?",
"Why not open carpark on G/F?",
"How to value a shop, when it is subject to 10‐year lease, used as supermarket? Do you need to take into account of long lease term when finding comparables? What is the yield?",
"Since Henderson has its data for rental transaction, do you think this is why they value at a higher price? Why the second bid is 30% lower? Is there any hope value? Is the tender price considered as market value?",
"The construction work of this site has been started, what’s the point for you to do the valuation again?",
"What information do u have when u conducted this project? What kinds of information has been provided by the agent?",
"It’s very uncommon to have such great variety of flatmix in APC, why did u propose so",
"Your studio unit has the highest unit rate, why not provide more studio unit?",
"Why not allowing seaview unit for all of your flatmix instead of particular having seaview on 2BR and 3BR unit? Can suit even more target buyer.",
"Can u explain more on holding cost adjustment?",
"How can you justify the 2.3% holding cost adjustment?",
"This site is formerly transacted, why not directly using direct comparison method? Please show your analysis.",
"It’s risky to transact by company share, do you understand why? Why not reflecting such factor in both of your direct comparison and residual valuation?",
"Can I see the analysis for the other two land comparables?",
"What is the use of sensitivity analysis?",
"Its quite common to have “provided at cost” in landsd, but you are now working in private sector, why using the same approach?",
"Why 4% marketing cost? How realistic that having 3% agency fee can be marketable? So many marketing experts in your company, why still adopting such low %?",
"Do you think Impact assessment are costless? Where did you Include? Do you know exactly how much for one impact assessment?",
"Your BC is approaching, do you really have enough time to finish the project?",
"How can you proof that your pre‐construction period allowed is justifiable?",
"21. What’s the months allowed from getting OP to CC?",
"You need to have professional integrity, right? But why are you disclosing all the confidential information to us now?",
"There are NIA and AQIA clauses in the C of S. Is there any impact to your proposed development?",
"Why you adopt 5% market cost?",
"Why you adopt 5% deferment rate?",
"Why do you follow Eden Manor (EM)’s flat mix and flat size (i.e. more large size units than small size units) in your hypo scheme?",
"Then why the smaller units have a better sales performance than the larger units?",
"EM has house type developments. Did you consider proposing houses in your scheme?",
"How did you arrive the GDV of CPS?",
"Did you consider the impact of “restriction on alienation of CPS” for your CPS comps?",
"The difference in F‐F height of the Subject (3.45m) and Royal Green (2.8m) is significant. How did you consider the difference in your adjustment?",
"How did you do adjustments for your special units?",
"How large is the size of your special units and the roof?",
"If the scale of your site is much larger and the developer has to pay government rent, what would be your consideration in your valuation assessment?",
"Name 5 valuation methods",
"Assume you are working for PCCW. How would you assess a data centre.",
"Explain the workflow of profit method",
"How would the property price change if interest rate goes up?.",
"You are the head of the valuation department in your company and you are the one to sign the reports. Assume that you have a client who holds many types of properties (Resi, office, hotel, etc.) and you do not have the expertise in the hotel sector, what would you do?",
"I see you made an adjustment for holding cost for 128 Waterloo (a pre‐sale comparable), can you briefly explain what it is?",
"Can you clarify why the unit rates adopted in your residual are different from the unit rates stipulated in your report?",
"I see you didn’t maximize the building height in the After Scenario, why not maximize the height as the unit rate of open view unit is much higher?",
"Do you think the site is easy to approach from MTR?",
"With the good accessibility, do you think there is potential for your site to provide small‐size unit instead of the current proposal?",
"As the site area is small, limited no. of CPS can be provided. Do you consider the provision of smaller‐size unit would be more favourable?",
"But there are rising trend in the subject district to provide 1BR units?",
"Professional fees in both scenario are the same, why? But development scales in both scenario are different?",
"What is the purpose of this exercise? Assessment of land premium payable to Lands Department or the market value of the site under both scenarios? Would the figures be different?",
"Assume economic condition back to normal, if you do valuation again as at current date, what changes would you make on the valuation model?",
"Why not provide balcony and utility platform in your assessment?",
"If you need to conduct valuation for an agricultural land which is used for open storage, how would you carry out your valuation and which valuation approach would you adopt?",
"Should the use of open storage be taken into account?",
"Is there any case where the value of open storage use which is commencing after the implementation of DPA plan can be taken into account?",
"If you have a R(A) site in urban area with non‐offensive trade clause, what kind of modern trade is to be disallowed under this clause?",
"How about bakery shop? convenience store?",
"If you work in a small developer and your boss plans to buy an old building where your family owns a unit. Your boss asks you to carry out feasibility study, will you do?",
"If you are the only surveyor in the firm? It might also be a benefit to your company that your family can be persuaded by you to sell the unit?",
"Now the boss accepted your valuation and made offer to your family. Your family asks for your advice, what will you do?",
"Will you teach the valuation approach?",
"Show me your direct comparison analysis. There is only 1% difference between your adjusted AV and the AV you calculated from residual, tell me why you don’t directly adopt the Direct Comparison Method. It should be the best valuation method.",
"What kind of adjustment did you do to arrive such adjusted AV? The location of FSSTL 279 is worse than your subject, why do you adopt 10% discount on it?",
"Can you tell me how did you do the time adjustment for land comparable",
"I can’t obtain the total adjustment by adding up your adjustment factors. Why?",
"Why do you use multiplication then? What is the relationship between each factor?",
"Have you consider house scenario?",
"I think that area should provide large size units but what you proposed are 1‐2BR units. I don’t agree with it. Explain it to me.",
"L: According to the figures, all the studio to 2BR units in Eden Manor were sold, then why don’t you propose studio?",
"Studio were 100% sold in Eden Manor. It is still not convincing to me that not to propose studio unit.",
"Have you use any 1st hand comparable?",
"How do you do CPS ratio adjustment for your residential CPS comparables",
"Why do you propose transfer plate as you already mentioned that your site could enjoy unobstructed golf‐course view, what is the function of it?",
"I saw you have adopted 5% on development scale. Do you think larger development scale is important in such area that could enjoy golf‐course view",
"Show me how you come up with such no. of CPS now. I can’t get the number as what you proposed. I only get 63 nos. instead of 75",
"Tell me about the implication of the latest JPN",
"Nowadays the saleable area for houses are usually greater than its GFA, do you know why? Do you know if there is difference between the definition of SA between code of measuring practice and Cap 621?",
"Do you know anything about offensive trade? What is the latest measure?",
"What kind of opportunities and threats will be imposed to the professionals by the implementation of Northern Metropolis?",
"What is zonal plan? Since it is no longer available, how do you assess the land value of agr. land?",
"You helped your uncle to conduct a valuation for a site 6 months ago, then now a client asked you to conduct another valuation for the same site, what will you do?",
"If your client asked for a quotation for a valuation exercise and you quoted say $100,000, and then next day he come to you again and ask for price reduction to $50,000 for the same exercise for same purpose. You are the only surveyor working in that company. What will you do?",
"Can you tell me the layout of all of your comparables? Did you do any adjustments on the difference in layout on your reference units and comparables?",
"What is your flat mix? Why don't you build 2 larger units instead of 3 units per floor?",
"What is the deferment rate that you adopted?",
"Have you considered APP 152 in your proposed development? Do you have any supporting slides?",
"Have you considered providing service lane in your development?",
"1.Can you share with me about the latest practice about virtually unrestricted lease?",
"Can you share with me about Northern Metropolis?",
"Apart from market value, can you tell me 2 values in the 2020 HKIS Valuation Standard?",
"Can you share with me your view on lowering the compulsory sale threshold?",
"If you previously helped your uncle do valuation report on a property and now the client of your company ask you to value the same property? What will you do?",
"What’s the status of the lease modi",
"The current stage of the adjoining building, have you consider the possibility of amalgamation",
"Land Comps were disregarded, please explain in detail",
"One of your comp is presale comp, no adjustment",
"Payment terms might pose effect on presale comps, what’s your approach?",
"Regarding three PV were adopted, please explain",
"Despite the higher unit rate fetched by 3‐BR unit, it has taken a very very small portion of the proposed development, please explain? Follow‐up: not the optimum GDV?",
"Have you provided special units and why not duplex or simplex?",
"Do you think your proposed development is marketable?",
"Noticed the area on the western side of Waterloo Road? The PR is normally 0.6 and premium involved, what’s the reason behind?",
"How to valuate agricultural land?",
"Offensive Trade Clause latest PN",
"LandsD latest arrangement on Zonal Plan for ex‐gratia payment, your view?",
"Ex‐gratia payment for resumption in urban areas",
"Regarding HPA, what have to be considered? Orientation?",
"What’s your view on the expensive HOS in the market nowadays?",
"How would you dispose your subject site, which would be more preferable?",
"Assume your friend who is an agent, acting for the owner of the adjoining lot and you are helping your boss in disposing the subject site, your fds asked you for info.",
"How did you arrive at your overall residential unit rate?",
"I don’t think you should use building view as reference unit while there is river view. Why?",
"There are many sites on Kai Tak Runway. Will your development be marketable considering your developments have over 1500 units? Do you know about K Summit. They have 1000 units. They took a year to sell and the developer had to provide a lot of incentives. S is your marketing cost enough?",
"Can you tell me what the yellow area and pink hatched black area are? Who will manage the yellow area? What can you do on the non-building area?",
"Can all of your residential CPS be sold? What about the disabled PS? So all disabled PS to be designated out of Visitor’s PS and as common area? (",
"There is a clause for no alienation. Can you tell me more about it? Are there any similar provisions in land sale conditions?",
"Under the “No alienation except for one assignment” clause, developers can sell the awarded land to somebody else for profit. Do you think this is a loophole?",
"Have you heard of the land sharing pilot scheme? It is not very attractive to developers. What’s your view?",
"You work in the government and your best friend is in the private sector. If he asks you about an upcoming land sale, what can you do? What if it’s just your opinions and site information, not the value? How will you reply him? Just say no?",
"How did you come up with your common part? Are 2 lifts enough for your development?",
"Why did the tendered price and your assessed market value had a substantial difference?",
"Do you think the tendered price was a special value to the successful bidder",
"Can you build anything on R(E)1 on your site? If you are developer, will you try to develop anything on it? Can you also tell me the application process?",
"Is it a must to designate the STT site as public car park?",
"Can you tell me the ATS procedure?",
"How to achieve the highest value of the site?",
"Is it a must to provide CPS on the site?",
"What is ""house""/ ""European type house"" restriction? What if it is a bare/cleared site?",
"What is your view on Small House Policy?",
"Why did you consult RVD when processing CC application",
"An old man owned 80% of an industrial building in CDA zoning, please advise in terms of asset enhancement, redevelopment and investment purposes.",
"What is GN 365 364",
"You are working in RDS and assessing a compensation case, while the land being resumed is owned by your relatives, what will you do? What if your senior insists?",
"How did you do pair comps to find the GDV of the special units?",
"Do you think having a larger garden will incur a higher unit rate?",
"How did you get the GDV of CPS? I see that your comparables have very different CPS ratio than your subject",
"Why didn’t you consider using direct comparison since there is a sale site comparable right next to your site?",
"I note that the AV of your comparables in direct comparison ranges from around $40,000 - $70,000, why do you consider the AV of your valuation is reasonable?",
"What are the differences between STT and STW?",
"Tell me 2 measures of increasing housing supply in the recent policy address",
"Suppose your boss wants you to do a valuation for a site and your brother wants to buy the sale site and asks you to do a valuation for him as well. What will you do?What if you are the agent of selling site, what will you do?",
"Is CPS GFA exemptible under the planning regime (I propose aboveground podium carpark)?",
"Can you name some positive covenants under your lease?",
"Please give me some examples on how different clauses will lead to an increase in rent? How about decrease in rent?",
"What have you considered before you adopt the subject site for CPS STT?",
"Please tell me some aspects that a bidder should consider when bidding a STT CPS site?",
"There is an existing old building in the subject site with some units are still under tenancies leasing out to different tenant. How would this affect your residual valuation?",
"Name some pros and cons of using country park for future housing supply",
"What should I do if I want to turn an industrial building into a data centre?",
"What characteristics an industrial building should possess to make it suitable for transforming into a data centre?",
"How would the scale of a developer’s firm affect a residual valuation for investment purpose (eg what will be different if the same project is considered by a large-scale developer and a small-scale one?)",
"How about for determining market value? Would the scale of developer affect the valuation?",
"You conducted a valuation report for a client. Later RVD called you to ask for some information about the valuation. Would you provide the information to RVD?",
"How do you derive the developer’s profit?",
"If your subject is a commercial building, will you adjust your developer’s profit?",
"If your site is located in Kai Tak, will you adjust your developer’s profit?",
"I see you have adopted first hand comp with different payment terms. How do you make adjustment?",
"What is brownfield land? Anything to note for development?",
"Suppose you are the developer that hold an office building in Sheung Wan, now the neighbouring office building is on sale, how will you value the building",
"You are developer working on acquisition project and your parents are living in the building you are going to acquire. Your parents now ask for your opinions on whether they should accept the offer. What should you do?",
"What if your boss insists you to take up the task? Suppose you are the only surveyor in the firm.",
"Will you disclose interests to your parents?",
"Follow-up: How did you do the adjustment on building age?How? Did you consider other factors?",
"Did you consider court case about what adjustment the court adopted?",
"Can you adopt the result of RVD index change on the last AV to arrive at the new AV?",
"Did you consider the duplex unit?But at least higher unit rate?",
"Why adopt 10% developer’s profit?",
"How can you find the developer’s profit of other projects?",
"What if the construction cost changed?",
"If you value the land at the end of this month, will you change any figures adopted in your assessment?",
"Did you consider maximising the site Coverage? Why not 11/F?Follow-up: why? Efficiency ratio increased.",
"Do you think area of the site will affect the AV?",
"Did you consider the orientation factor?",
"Your comparables are composite buildings but your development is pure residential, any adjustment?",
"Is 25m² enough for putting one lift two staircases?",
"How do you come up with your development period? From when to when?",
"Why adopted $2m instead of $2.1m for your CPS coz the transaction date of the cps comp is closer to your valuation date?",
"Will you disclose the details of a case to your friend when he asked you?",
"Will you disclose L.I. to your friend when he requested you to give him?",
"Your friend is working in a consultancy firm and representing the applicant for the same case as yours, what will you do?",
"NF: How do you arrive your adjustments on flat roof and top roof?",
"What is your flat mix? Why?",
"Why did you allow marketing cost of 3.5% ?",
"Is it okay for you to build sales office on the site?",
"What do u know about the modular social housing?",
"What do you think of transitional housing as a policy?",
"RVD: Have you heard of Lantau Tomorrow?",
"is there only concern on the lump sum amount of the construction cost of Lantau Tomorrow? Any other concern?",
"If a lot has an existing building on it, what values would you assess?",
"If say there is an existing building on a lot, and there is a site adjoining to your site, how would you value the site?",
"If you are working for your boss, who is going to purchase your family’s home for their acquisition, would you still value it?",
"Can you help your family member in providing advice?",
"If the family member asks you about basic particulars, can you provide them with such kind of information?",
"Why do not adopt the discount on immediate payment as the holding cost?",
"Is there any difference in property value for open carpark?",
"What is the discrepancy between the government and developers in premium negotiation?",
"How will you value a shop as a supermarket?",
"What will you do if you have a job with expertise you do not have?",
"(D) Can you explain your time adjustment? I see that there are 2 comps which are only 4 days apart but the time adjustments you made have a difference of 2%, is it reasonable? Is CCL index reliable?",
"What will affect the investment value of CPS?I see that your comps do not have carpark ROA clause, how does it affect the investment value?",
"Have you looked at CPS rental and yield of your pair comp?",
"Can you explain your holding cost adjustment?Can you tell me the yield of residential units in Tuen Mun? asks you to change the adjustment to 2.5% (I adopted 1.5%), what will you do?",
"As shown in the info statement, PR relaxation could be obtained by developers through planning application and lease modification. What would be developers’ consideration when applying",
"10. (A) (Follow up Q9) Since the info statement did not mention how much PR relaxation will be approved by TPB, how can developers be certain that 20% PR relaxation may be applied?",
"How do you value data centre?",
"If a client has huge portfolio over Hong Kong, Macau and Mainland etc. and he asks you to do valuation for his whole portfolio, what will you do? If you don’t want to give up the project, what will you do?",
"What are the positive and restrictive covenants under your lease?",
"What are the terms that would affect the tendered rent?",
"What consideration have to be paid to if you are the prospective tenderer bidding the STT carpark?",
"Why did you only focus only the Temporary Uses under the OZP but not the Column 1 uses of the OZP?",
"What are the Classes of site under BPR?",
"Are you aware of the recent update on Valuation Standard? What are the 2 values defined under the VS other than Market Value?",
"What are the requirements of converting IB into Data Centre? (Lease, Building and Planning)",
"Supposed you have submitted a valuation report to a client for internal reference purposes. The valuation report was then submitted by the client to RVD for stamp duty appeal. Then, someday, a guy from RVD approach you by making reference to the valuation report and ask you to provide more comparables, what would you do?",
"Are there any differences between your hypothetical development and the approved GBP?",
"As direct comparables are not adopted, how could you be certain that the land value produced by residual valuation is correct?",
"What would you advice if the subject site is proposed to be used as transitional housing in the future?",
"Your friend working in LandsD always tells you the internal information in LandsD, and some are conducive to your valuation in URA. Would you use this information",
"Definition of Market Value",
"How to access to the roof area? Internal staircase?",
"(Follow Q4) Access by internal staircase means there will be a stairhood at the roof. Is the area of stairhood a kind of saleable area in a sales brochure?",
"Why only one transaction in one of your selected comparable developments?",
"Why not use Upper Riverbank as one of the comparables?",
"Why not use direct comparison of AV?",
"How does each of the items affect the AV?",
"Why no cost has been provided for Government Accommodation?",
"How the phasing of construction affect the GDV and cost?",
"How to conduct valuation of a hotel?",
"How to conduct valuation of a shopping mall?",
"How to get the yield?",
"Any effective and efficient ways to increase land supply in long-term, mediumterm and short-term view?",
"Why Land Sharing Pilot Scheme is not attractive enough from private sectors’ view?",
"What are the features of Industrial Revitalisation Scheme 2.0?",
"If your client asked you to conduct a valuation of a piece of land which was owned by your relative, what would you do?",
"You have a long-term client. After receiving your valuation report, he asked for a lower fee for your consultancy service. What would you do?",
"What is double-deck parking? Why not consider to adopt but build so many storeys of podium cps? 4/s, reasonable? What would lands dept comment? Abuse? Ddh?",
"What E&M is put on each floor? Reasons?",
"If I consider the revitalization proposal, the investment value would be lower, do you know why?",
"How to alter cps if building façade is fixed?",
"How would the cancellation of non-residential double stamp duty affect the residential properties in HK?",
"What is the progress of kwu tung development? Do you think gov is having a good progress on development of new land? what could they do further",
"What is Rebus SXX (rating)? When to use?",
"Apart from three development controls you mentioned, what else govern the developments in hk? which ones are more important?",
"What plant cannot be demolished?",
"Is service apartment classified as residential or hotel? Heard of case of Rambler crest? Why would the incident happen? Any insight from it?",
"Do you know that the premium to pay to gov for the NTEH in better villages would be lower than those in worse villages? Isn't that strange?",
"For clubhouse, how would you advise your client how large it should be built?",
"Why 15% developer’s profit?  Workback analysis of some",
"Why 4% deferment rate?",
"I noticed that the final tender award price is around 2X% higher than your assessed land value. Do you think your valuation is correct?",
"Is a fixed term of 1 year attractive to the potential tenants?",
"If you are the developer, will you propose car park there? (It is a residential development in Sham Shui Po)",
"If there is a bare land, for which the user is restricted to one European house under lease. What can you advise to the client for development?",
"Follow up, if there was a 6/S residential building before demolition. What can you advise for development?",
"If your client owns 87% of an industrial building which the age is 47 years, what would you advise him to do?",
"If there is an agent offering the client full EUV or RDV with discount, what would you advise, accept or not?",
"I noticed you assist in valuation work at Lohas Park, so what is “Greenfield” basis?",
"Will “Greenfield” basis be taken in account when assessing total development cost and development period?",
"Assume you are working in RDS, you are doing a compensation task of a building land. The land is owned by your relatives. What would you do?",
"Follow up, if there are no more staff to handle this task. What could you do",
"Floor Level? Is it linear?",
"Your CPS price seems low for before scenario. Compared to after scenario, it has a smaller ratio, why is it even cheaper?",
"Have you considered incorporating bonus GFA/GFA concession in the hypothetical development?",
"Is it always true that large units have a higher unit rate?",
"I saw you showed you break down the construction cost in very detail, unlike other candidates, why?",
"In To Kwa Wan, some sites are subject to two height restrictions. One lot is 80mPD and the one is 50mPD OZP. It is rare, but how would you approach it?",
"Do you know three schedulesa in BPR? What is their implications in you development?",
"Barrier Free Access would affect the value of the property because it takes up space. But ut us necessary under BPR. How would you approach it?",
"Do you know dedication and surrender? For your site? Which park would u consider to dedicate or surrender?",
"What would you suggest to the GPD? In terms of CPD?",
"You are the only contact person from agents. One agent is your close friend. If he offers to you, what would u do?",
"You found some mistakes in previus valuations in a company. You told your senior but he asked u not to disclose it, the company will close down and many employee including you will be jobless!",
"What is the implication of the type of an apartment building of an European Type?",
"Why is there no provision of Clubhouse even if there is concession GFA for before scenario?",
"What does pre-construction period include?",
"Why is construction cost for apartmrnt for 'After' scenario different from 'Before Scenario'?",
"Why don’t you adopt unit rate of en bloc apartment transacion comparable as the GDV for "After Scenario" Directly?",
"What dows the tenant need to do if he wants to remove trees on the site?",
"What is the impact of longer or shorter duration of fixed term?",
"What will you consider when doing revision fo rent as a landlord?",
"What are Consent to Assign and Certificate of Compiance",
"What are the requirement for obtaining Pre-sale consent>",
"Whatr is the Residential Properties (First-hand Sales) Ordinance about?",
"What does you need to consider when selecting first-hand transaction as sale comparable?",
"What do you know about Cap. 545?",
"If such GA is good incondition and it is not a must to demolish it, what will you do?",
"What do you need to do for CDA site",
"Have you consider zoning in direct comparison?",
"Assume there is a site comps with very similar characteristics, except ther is no seaview, will you adopt it?",
"What is the constrain for using presale comparables",
"What is the difference between deferment rate and interest?",
"Assume the developer is borrowing money from the bank, which valuation, yours or final tender price, should the bank adopt? Why?",
"You will provide show flat, so is onsite or offsite",
"have you considered when you sell your proposed development?",
"You say you will provide offsite show flat, but you will not provide any pre-sale scheme, then is it logical?",
"Which method will you use for basement car parking space",
"it Is a very large car park, other than direct comparison, what will you do?",
"how can you find rental income and yield?",
"will you consider occupancy rate?",
"will you consider occupancy rate when adopting yield?",
"What is a Class A site? What are the definitions of Specified streets",
"Is there any impact on your development due to lack of vehicular access?",
"Is the plant room cost included in your valuation? In which component>",
"What is the future planning of your STT site",
"If the tenant of the STT carries out illegal/unauthorized uses on the site, what will the government do to penalize tenant?",
"What is your view towards vacancy tax? Will this cause unfairness to developers?",
"If there are redevelopment projects under Cap.545, does the developer need to apply for CC after completion?",
"Cam you tell me more on the JPN 5 about buildin gheight restriction? Will there be loophole>",
"What are the consequences if the developer stops carrying out construction works of the sale site they bid? I observe that some developers bid the sale site and resell it to other developers by transferring the company shares, do you think thee are loopholes of current policy?",
"What is asset enhancement?",
"Can you tell me the difference between no-objection letter and short term waiver?",
"How do you assess the value of land if there is an existing building?",
"Have you considered the podium car parking level when you considerd the refernce floor?",
"Show me your professional fee break down.",
"If the development scale is larger, profit will be larger or smaller",
"What is the statutory requirement for BA approving building plan?",
"What is difference between temp waiver and short terrm waiver?",
"How to Value public carpark?",
"Which on have higher risk, IB or public carpark?",
"PPl is worried that the lease will be expired in 2047, whats your opinion?",
"Which practic notes sets out measures reagrding Green Buildings? What is it about and how do you get extra GFA for those features?",
"Definition of Greenfield adjustment and how to come up with 20% adjustment?",
"Have you geard of the HKHS new measures to encourage household to rent separart bedrooms out>",
"In this market atmosphere, how do you do shop valuation given the lack of market evidnence and how would you come up with the yield?",
"There are 4 class of Government rent, what are they?",
"How to carry out valuation for haunted units? How do you know it is haunted?",
"What is the Schedule 1,2,3, of BPR",
"Suppose your boss asks you to sign a valaution report which the value is higher than your proposed value. Would you sign it?",
"Have you done any market research and what is your benchmark deevelopment in formulating hypothetical development? Why not follow the existing development flat mix?",
"What is the difference of private residential use, service apartnent and hotel?",
"What is VR lease, what is non-offensive trade clause",
"What is BC clause? Why clear site value is used in assess BC premium>",
"Why refuge floor needed in the development? ",
"Why a higher headroom affects common area and staircase? Any difference for single bug staircase and two separate staircase?",
"Why no curtain wall stated in residual as usually new development have",
"What is the scope, criteria and view on rating amendment bill in Sep 2019?",
"How and how often RVD check the vacancy? Why didn’t exemot Class D and E unit?",
"What is your view on Industrial Revitalizatrion",
"What is conflict of interest?",
"If you finished a valuation and submitted to client, after 3 months, the client ask you to be agent, will you take the job? What if after 2 years?",
"What is the purpose of your valuation? Assess the lease modification premium or enhancement in land value? I notice there are differences between your valuation model and lands D model. Can you explain the difference to us?",
"Have you compared your prenmium assessment with the past lease modification cases? What is your analysis on that?",
"Have you heard about a court case about one house? Does the court decision apply to you case?",
"What do you know about First Hand Sales Ordinance? Does the Ordinance define SA? What is the definition> WHt is included in the registered of transaction?",
"For how many years a development would be considered as a permanent development>",
"Did you make reference to the rent of carpark STT in the nearby STT site?",
"Any special term in your TA? Like did you consult any department>",
"What are he considerations when landsD award tender to a tenderer? Would the consideration be different if the carpark is owned by private sector?",
"A shop has UBW, you need to do valuation for it, would you take UBW into account> What if the valuation it's for compensation assessment and for rating purpose collectively?",
"The government introduced policies to provide starter hones and transitional housing, what is your view on that policy?",
"Do you think government should conside selling the West Kowloon topside development in serval parts so that more developers can join the bid?",
"You are the sole agent of a property, now your client want to appoint you to do valuation report for the same property as well, would you accept the valuation job? What if the client insists? How about assigning the valuation job to another team in your company?",
"Is your podium carpark GFA accountable?",
"Your land sale comparable has a PR much higher than that of you subject site while they are within the same OZP zone, Why so?",
"How to assess rental of a hotel?",
"An investor is seeking your advice on changing an office building into hotel. How would you advise.",
"An investor is seeking your advice on investing a car paring spaces with 200M How would you advise?",
"A group of company is planing to rig a Government tender and invites your company to join.What would you do?",
"What is the implication of APP-151? Any additional SA you have considered?",
"How much gradde would you want to acheiev under BEAM Plus?",
"Why u don’t also consider curtain wall? Because if use, it can add you 200mm more SA?",
"Any implication of the Schedule 3 on your residual valuation?How?",
"Do you know about PNAP APP 132?",
"Do you think the profit more of a cost of finance than opportunity cost?",
"Do STT requires to pay rent and rates>",
"What else do you think can improve the image of HKIS especially GP division?",
"Assuming I have a relative who partnership with 3 more associates to form a company. Now your relative wanna quit and would like to dispose his holding shares to the other assocuates. He asked you to help do the valuation of his shares?",
"What is the implication if I propose a domestic floor with 4m headroom",
"What is implication to common area if the headroom is 3.5m",
"What if the subject under BC extension is put on sale in the open market, would it fetch a different price than a normal site?",
"Did you take into account the subject's approved building plan during valuation?",
"Why there is no service lane in your development",
"When do you need to provide two staircases",
"Why do you adopt above ground caraprk instead of besement carpark",
"Why LandsD use CSV to assess BC premium?",
"Do you know why the owners usually prefer redevelopment for new industrial use unstead of office use if they are seeking 0% additional non-domestic GFA?",
"What is Special Rates under the amendment of Rating Ordinance?",
"What the developers need to do and who is responsibel for collecting the Special Rates?",
"Which on do you prefer? Reclamation or developing country parks?",
"If you bave done a valuation for a property and your clinet asked you to be the agent for the sale of that property. Would you accept>",
"If you have done a valuation report for a property and after 5 years, a bank fins you for revaluation? Would you do it?",
"Any existing building on the lot? Will u calculate the EUV if there is? What if the EUV is higher than RDV?",
"Will you provide houses in the before scenario?",
"How do you justify your efficiency ratio of after and before?",
"Are you involved in premium negotiation process>",
"How do you assess the transaction price if there are rebates involved in the transaction?4",
"What is without prejudice",
"What's your view on vacancy tax?",
"Do you think the administrative cost is high for vacancy tax>",
"DO you know the office rental in Central? How about Kwun Tong/Kwoloon By",
"Have you considered agent reabteing agent fee?",
"Why there is no provision of caretaker;s office and quarters in before scenario",
"Did you read the lease? What's the lease type? Is this a lease modificationcase? Any difference between before and after scenario?",
"Direct comp: How do you arrive time adjustment? Why don’t you put the adjusted GDV in a residual valuation to find the difference in time?",
"View on arbitration for premium negotitation",
"View on redeveloping co-op by government",
"View on BEAM",
"Tell me the definition of height under BPR and under lease, Whats the difference",
"Tell me what works can you do when you doiing NIA, SIA assessment. What if the government don’t approve SIA&NIA",
"If there is no difference, will there be swimming pool in your special units?",
"Tell me about what's CC, how is that important",
"If now I have a piece of land and want to develop, what will you advise from the planning control perspective?",
"What if the s.16 application got disapproved? Is there any appeal mechanism, tell me about that.",
"What is the most effective way for land supply?",
"Tell me how to do valuation on a hotel/",
"Are you familiar with DCF?",
"If now someon needs cash and he intends to sell his hous in the peak, then he wants to appoint you to be the valuer as well as the agent for his property",
"Why do u think need to separate profit on cost and profit on land?",
"If you only adopting profit on GDV only, will you adopt same % for the profit?",
"What do you know about the difference between CDA use and R(B) use under OZP?",
"Have you consider contiungency in your residual valuation?",
"What do you think are the pros and cons for adopting residual valuation?",
"The tender was closed for the data centre yesterday. Can you suggest what valuation method you will use If you are a developer and if you are google.",
"Can you tell me some policies which suggested by the government before the policy address?",
"Did you consider valuing the GDV of the subject lot by summation of all prices available on Yuccie Square price list?",
"How do you comment the current housin supply in Hong Kong? What is your advice to increase housing supply in Hong Kong",
"Online shopping is of increasing trend nowadsays. Meanwhile, may infrastructures such as Hong Kong-Zhuhai Macao Bridge. How would you comment to future retaill market in Hong Kong?",
"Suppose you ae appointed by a client who owns an office building in Hung Hom with occupancy rate of 90%. Your client intends to change to office building to hotel and seeks your advices. ",
"How do you come up with your external works costs",
"Cost for external works is nearly 10 times than that of Open CPS, but they are all open area. Why is there such a differnece.",
"Item PL1 has similar location and site area with your sbject, and it is more stringent than you Before Situation in terms of lease restruction. But the transacted lump sum is higher than your before value, why?",
"Why no covered CPS for before situation",
"Now only consider your before valuation. If there's an existing building, how does it affect your before valuation?",
"What do you think about recreational lease and reclamation?",
"What are your expected Avs on future runway sites? What's the difference between the runway sites recentlysold and the runways sites to be sold on Jan? Any difference in lease conditions between Kai Tak sites, SHK sites and runway sites?",
"You said the market is unstable. But the sale of Grand Central seems reflectig the contrary. How do you explain? Do you know how the payment terms of 1st hand sale properties have been changing in this year?",
"If no redevelopment potential, how to value? If it is being used for open storage, how to value?",
"Open storage legal or illegal? If illegal, how to make it legal?",
"Can I do restaurant, Can I do 7-11",
"What did you learn specifically from this project? I think your descriptions in Lesson Learnt are too general",
"What is CDA Zoning and planning brief?",
"Should you adopt comparables after your valuation date? How about for a dateback valuation? If you are asked to conduct the same valuation at today, will you have the same result?",
"What is your opinion on the difference between Government residual model and private model?",
"Talk about one hous restriction. Do you think it is unfair for developers for Government to change their approach after the court case?",
"What are the criteria for filing a Cap 545 application to LT and what LT consider",
"Your view on the trend of future prime office price?",
"Talk about the future supply of office space in central",
"Did you try out different hypo, why?",
"What is the procedure for applying NTEH?",
"What is the difference in applying NTEH when the villager has agricultural land and without?",
"Will shop yield higher than shopping arcade? Why",
"What is yield",
"What is the difference in special waiver and lease modification?",
"Is Cap. 124= Open market value?",
"Why do we need circulation between gov. departments",
"Why cant u use V Zone for building NTEH?",
"Do you think the current STT procedure is fair? Why do you review it 3-5 years? Why cant it be 1/2 year?",
"If URA appointed colliers and you work for colliers, before agzette so things are confidential, your colleague ask you the price for special unit, can u tell? If no why?",
"Why do you adopt 5% as deferment rate? Why not use all-risk yield instead of prime rate for deferment rate?",
"What is the definition of SA, Should bay window be counted as SA?",
"In non-domestic units, what area can aslo be used for measurement besides SA?",
"What is ratable value",
"How could you use gross rent to achieve annual rental income?",
"Lets say there is a 3-year tenancy, what would be the effect of having break clause and rent raise provsion at the same time?",
"What is carpart area",
"You are instructed by your client to carry out a site inspection that he says he is the owner. But you could not find the site during inspection. What would you do?",
"You are instrutcted by your client to value an agricultural land that he wishes to purchase. During the site inspection, you see some occupiers with illegal building structures. What would you advise your client.",
"The agricultural land that you required to value has no vehicular access. How would it affect your valuation and its development potential.",
"Can you briefly introduce surveyor's duty to clinets in the Rule of Conduct?",
"Your development period Is 6 years, please explain why your PV for construction cost is 4.5 years",
"",
"What do you think would be the difference in doing a valuation for mortgage purpose?",
"Please tell me your understanding on the Pre-sale Consent Scheme.",
"What is the difference between s.12A and s.16 Application",
"Under s.16 application, what can you apply to change",
"Please tell me about your view on vacancy tax? Why did the government set OP not CC.",
"Can you tell me more about lease modification and technical modification?",
"If the two sites after exchnage still subject to 2 different height restrictions, what will be the maximum building height of your development",
"You have mentioned the NTEH, do you know the restrictions under building ordinance regulating NTEH? Can you name it?",
"What are the differences between the Cap 121 and Cap 123F",
"If you are agent, assume you don’t know it is the haunted house, do you need to disclose to the client?",
"If your client wants to purchase a building, the building straddles the adjacent private lot as shown on the lot index plan which is not the seller's lot, what will you advise your client",
"If you area representing LandsD to give professional evidence in the court, you have duty to who? Not LandsD",
"Is there an way to appeal if I don’t agree with the government;s BC premium?",
"If there are two similar flats but the rental of one is signifucal=ntly higher than the other flat, what would you do?",
"Will there be any difference between conducting valuation on haunted units for mortgage purpose and rating purpose>",
"If the same colleague approacheds your boss to know about your report, what would you do?",
"Is your design (podium SC smaller than residential accommodation SC) feasible in reality? Have you consilted your QS consultant about this?",
"You mentioned the term hypothetical development. Is there any difference between hypothetical development and optimal developent?",
"Do you know the difference in cost between a phased and non-phased development?",
"For construction phasing, can the money obtained from the first phase be used in constructing second phase?",
"What is the definition of GFA? Why include Greenery under non-accountable GFA in your developmen schedule?",
"Why PV twice? Why PV period is half for cost?",
"Why 5% prime rate? Do you know there is more than 1 prime rate>",
"Is the transaction date in your comparable all SAP/ASP date? How did you confirm this information?",
"Are STT carpark accountable for rates and government rent? Do you mean all special properties are not liable for government rent?",
"What is the difference between passing rental and market rental",
"Then what is the difference between market yield and reversionary yield?",
"If you are estate agent and you are asked by your boss to work for both developer and client, what will you do?",
"Why your residential comps range is so wide?",
"Bloomsway, as a presale comps, did you consider discount in terms of stamo duty?",
"Any concern for presale? What docments needed to be submitted",
"What is DMC",
"Would you consider other user for your STT?",
"How did you value the STT",
"If other department proposed other use,would you consider it?",
"About providing flats at the Kwai Chung Container Terminal, what is your view for government and for planning, do you think the governemnt should consult publuc for this or other land supply measures",
"What is your recommendation for the government to increase housing upply in short-term?",
"People are protesting against the Link for severely rising rents and adversely affect the local residences' loves. Do you think the government should buy back the malls? How would you reply the media if needed to ?",
"As you think the prospect of office is good, do you think the government should increase office supply? Or do you think the government should not intervene the market?",
"The land sale comparables share same attributes including user, zoning, plot ratio, site coverage; the only difference is site area, why adjustment is not possible",
"Direct Comparison method is the best method for valuation, while reidual valuation invovle lots assumptions, do you think adopting residual valuation is a better way?",
"Did you applid JPN for your assessment?",
"BD PBAP changed in 2015, please tell the differences and how's affect your valuation as your comparables building plans are approved before 2015?",
"What is the difference between tenancy and licence",
"What is the difference of the valuation basis between URA offer and government offer?",
"I see a few of you use the same project for the APC. Are you cross-checking with each other? Please explain",
"What's the mortgage rate now? Why don’t you adopt this figure?",
"With your current GDV; if the market is good, you cant bid the land, if the market is bad, you are overpriced how do you explain?",
"What’s your building spec under your proposed construction cost",
"Do you know what is Management Share? How to calculate maagement fee? Any difference in calculating management fee if is composite buildings - say retail portion/ residential portion?",
"How to advise your client to turn an office into a restaurant in a commercial building? Supposedly no restiurction on lease",
"Suppose two clients, one is the seller and one is the buyer, ask you to value the same property at the same time, what will you do?",
"Have you considered the distribution of undivided shares of your sibject site upon completion?",
"How will you calculate the manegment fee of your sibjet site ipon completion? How;s the management fee of the common area going to be calculated?",
"If your site car parking provision maximized? Why not more CP?",
"WHt don’t you submit a planning application to permanetly change the use of STT CP instead of retendeing it after a certain period of time regularly?",
"Have you considerd ising it for other purposed than CP to maximize the site value",
"What happen if the tender submitted lower than the reserve price",
"How many vehicles exactly can this site accommodate? Whydo you allow heavy vehicle parking, is that more valuable?",
"How do you do a valuation for a shop with an illegal structure? For leasing purpose and sales and purchase purpose.",
"If both parties approach you for marketing and acquisition of the same property, what would uou do?",
"What do you mean by optimal hypothetical development? What is the definition of principal dati/",
"How did you cross-check the land value derived by residual valuation method with the result from the direct comparison method given that the qualitative differences among the land comparables are hardly quantified?",
"Which comparbles are 1st hand transaction? The transaction date taken is ASP or PASP?",
"Do you know the other  methods in assessing land value> What is the difference between initial tield and equivalent yield? Is the initial yield specific to the developer?",
"What are the difference of unit of these transactions? UFA, GFA, SA",
"What is the difference of the unit commonly adopted for offices in HK Islane and Kowloon area?",
"What are the circumstances to insert government accommodation in the lease conditions> what are the obligatuons under such clause and usually when will the liability be released?",
"How about using cargo terminal",
"How about 貨櫃屋",
"I saw you sttended a cpd called Smart city.What is it and how it related to your working?",
"Do you think it is enough for the headroom of typical units after deducting the thickness of floor slab?",
"Why do you mean by provide at cost?",
"Have you considered using transfer plate in your proposed developent?",
"Do you think anti-speculative measures should be less tighten up?",
"Have you considered Reduced Zoning Method?",
"If there is no assumption on clear site basis, how would you condict your valuation? EUV or RDV",
"How to fulfill BC? Is getting an OP or care-takers'quarter enough to fulfill BC? ",
"Resumption, whether UBW will be taken into account",
"Definition of saleabel area",
"Is the subject site affected by noise? What are the mitigation measures?",
"If the final lump sum for the comparables involve any rebate from the developer? What are the payment methods? Have you deducted all the discounts for your final lump sum price?",
"Do STT carpark allow vending machine? Any approval is required? What will DLO do if such machine is provided? What if there is demand for a kiosk in your STT ,what will you do? How to value STT with a user of CPS and Kiosk?",
"There is a site with 3 flats on a lot subject to one house restriction, what is the implication? What can the developer?  What is the consideration of modification of the one house restriction that has premium implication? (Fully profit)",
"Do you know about Hysan v TPB case? What is the implication towards the decision of TPB? Do you think TPB would change its decision?",
"What are the circumstances to insert government accommodation in the lease conditions> what are the obligatuons under such clause and usually when will the liability be released? ",
"What is ratable value? What are the assumptions for assessment of RV? Who should pay the maintenance fee/ maintenance responsibility of the building/internal repairing? What is the valuation date for 2016/2017 RV?",
"If are the effects of US increase in interest rate on property market? What effects will there be on the yield on the property market? What are the implications on its value and rental?",
"Referring to your residual valuation, no contingency cost was allowed. Why?",
"Do you think that the reuqirements of HKPSG are unrealistic?",
"How do the future land and flat supplies affect you valuation?",
"Do you think there is necessity to use the land of your STT as carpark? Have you consider other purpose?",
"Ther should be some carparks available in the residential developments nearby. Why cant park in these developments instead of your STT carpark?",
"your STT is granted by Tender. Is there any other way that STT can be granted?",
"When will STT be granted by Tender? When will STT be granted directly.",
"Assuming that you were appointed by a client to carry out a valuation on one of his property. You finished the valuation properly and your job was done. After two months, you client come back to you, and he said that his brother appointed another surveyor to assess the value of that property. However, the value assessed by that surveyor is different from the value assessed by you. He asked you to help and explain such difference to his brother. What will you do?",
"what is the most difficulty in your project",
"Why do you adopt 2-phase development? Do you think 1 phase construction cost is more expensive or 2 phase construction cost?",
"If owner wants to combine two units, what do you thiink?",
"There are private developers, URA and the government in the market. While the URA has been supported by the government, the private developers are not assessed by the government. Do you think it is unfair?",
"What would you do when you want to have higher development potential?",
"What is the difference between urban OZP and rural OZP?",
"What the GP division can do to promote the image of the institute?",
"your STT is granted by Tender. Is there any other way that STT can be granted?",
"Your former colleague, when acting for a client, had made a fatal mistake in a report that would lead the company collapse if the mistake is discovered. And now your boss who knows the mistake come to ask you to follow the case for the client and ask you to keep secret for the mistake. Otherwise, the company will close down and you would lose your job. What would you do?",
"Have you considered a mixed development with houses and apartments",
"What does the lup sum per unit tell u",
"Why don’t you prpose carpark on upper floors",
"If there were existing buildings on site, what differences would you make to your residual valuation or hypothetical development?",
"Any more recent Government tender sales apart from these?",
"You discard the direct comparison approach on the basis that it is too hard, but the AV of your assessment is only about 4% over that of the land comparable. Are you still comfortable that the comparison approach is not relevant?",
"You adopted the prime rate for the deferment rate. What is the cost of financing supposed to represent? Do developers borrow at the prime rate?",
"Assuming the Government announced to put more flat supply in Ho Man Tin. Would you make any changes to your residual valuation? Which factors would you like to revise",
"Would the Lands Tribunal’s decision become evidence of value?",
"What is the duty of an expert witness?",
"Why would the Government use tender as opposed to the private treaty negotiation?",
"Would tendered evidence be evidence of market value?",
"Would the results of R&E and DCF methods be the same?",
"Do you think the 15% stamp duty recently imposed by the Government would have a great impact on the residential market?",
"Assuming the policy was launched at the time before your valuation date, would you make any changes to your valuation?",
"What would you do if your boss asks you to do a valuation at a particular price",
"Did you allow any facilities adjustments for your comps?",
"Why didn’t you incluude ant rental valuation for the STT in you report?",
"Why did you adopt a fixed term of 1 year for your Subject STT?",
"Do you know RZA? It this still applicable in valuation of Shops in Hong Kong? ",
"Should illegal structures be taken account for the valuation of shops?",
"Now your client asks you to prepare a valuation report, how would you do to aviod any conflict of interest?",
"What is your valuation date? The premium should be paid after or before this date?",
"Some people use full interest rate to discount half of the construction period, while some may use half interest rate to discount full construction period. Do you know the difference between them?",
"Will you adopt different profit margin for different scale of development? So you are assuming the profit for a large, medium or small sized developer?",
"If there are no carparking provision under the lease, will you still provide such no. of carparks?",
"Have you made adjustment for orientation? Have you made reference to any court cases?",
"Why the GFA of recreational facilities not exempted under the lease?",
"Do you know anything about the white book of this regulation? (first hand sales)",
"The punishment will be on director’s grade or front-line staff?",
"If the tenant agreed to lease the property for 3 years (oral agreement), but now he wants to change the lease term to 5 years, what will you do?",
"So will the vacancy rate increases in Kowloon East with the policy of revitalization of industrial buildings?",
"Is there any relationship between the office market and the residential market?",
"Noting you have selected quite a number of comparables, and the range of adjustment varies greatly, do you just average the adjusted value or you select comparables with less adjustments?",
"The GDV adopted in your valuation, is it present value or future value?",
"Do you think there’s a difference between 1st and 2nd comps, should you use pre-sale comparables?",
"What factors will you consider other than nearby developments and market sentiments?",
"Is it a must to provide show flats?",
"How about the sale of a new single house, is it a must to provide sales brochure?",
"What are the valuation principles in cap. 545",
"What would you advice your client if s.16 applicant is rejected? What if it is rejected again after s.17?",
"What is the major factor in shop valuation?",
"Do you know if there’s any planning control on resumption?",
"What are the effects on US raising interest rate on shop yield?How long will the effect that you’ve mentioned last",
"What would advice if your client wants to invest to shop on Russel st",
"Say, if Paul Chan announced that a large area in PSK will be included in the coming land sale programmme, if you were to value this piece of land again, do you think the value would be different?",
"did you apply any adjustment for the church located nearby?",
"Did you apply any adjustment for the electrical substation located nearby?",
"How will you amend your market value assessment if your site is under judical review?",
"Do you know how to measure headroom? Do you know what is the normal headroom for residential development in Hong Kong?",
"Does the construction cost you adopted for carpark reflect higher construction cost for basement carpark?",
"How would the future supply affect your market value assessment",
"What is the common claim made under Cap. 370? What is the basis of valuation for road closure?",
"If carpark is not permitted under column One, what will you do?",
"If your assessment for a lease modification is 550M while the offer from LandsD is 500M, Would you accept the offer as it is lower than you estimation> What are the factor affecring your decision?",
"Where is the cost ofor plant room, OC office? The area is quite large, and you think the cost is zero?",
"There are CDA sites in Whitehead. How would you value? How if there are no approval scheme for the CDA",
"If I change a flat roof to garden use, when it can be GFA non-accountable?",
"Do you know current market movement in Tung Chung",
"How dies the accessibility of MTR affect the unit rates of flat, CPS and land sale?",
"What do you know about stamo duty",
"But this is only the construction period, not the development period; do you know how long does it take to obtain OP and CC?",
"What will be changed if you do case again as at today? Which component would have the largest difference?",
"Do you know any whold block office transaction in CBD recently? Do you think the price is above market? What’s the payment method?",
"How would you explain the difference between AV betwenn your assessment and the land sale comps?",
"What are the limitation of applying RVD property index? Apart from RVD index, what other methods can you adoot for time adjustment?",
"Did you alow any cost of stamp duty for the land sale in your calculation?",
"What's your role in re-tender STT exercise? Did you add any new clause or just cooying from existing STT TA?",
"Can you exlain the latest news about the small house policy? (套丁)",
"What do you know about GN364",
"You have mentioned three main development controls and can you state any other control?",
"Do you know special controls governing Pok Fu Lam",
"What is the difference between the yield adopted in term and reversion> Under what scenario will the yield of term would be higher/lower than that of reversion?",
"What is the difference between road and street",
"If you are hired to provide professional evidence in court, who should you be responsible for You act in the best interets of our client?",
"Can you tell me your PR regarding the BPR?",
"Would there be any implication on your assessment if your subject is under judicial review?",
"I'm curious to know what is the basis for calculating licence fee for underlying water cable",
"What is the ost importatt factor for C of C",
"For a lease modification case. How long would the premium be offered by the government?",
"Is railway reserve clause imposed on your site? Any protection boundayr? Any implication?",
"Maybe when you take bus/minibus at those comps there are vacncies but when you take it at your site it may be full. Did you think of that?",
"How did you consider about the internal state of repaur for building age adjustment",
"You figured out that the GDV difference between direct comp and residual valuation is so small so that the land comp should be relevant…",
"I know what you said are the interpretations from the lands Department according to the Practice Notes. Whar is the court judgement?",
"Do you know of any recent whold-block office transactions? Who are the purchasers?",
"If you include the comparable development in your paur analysis of size, would they also show the same degree of difference?",
"Normally people would put a larger size for a better view. It seems that the size and the view got a relationsip as well. How you distingush those two when you do analysis>",
"What is the group of customers that you are targeting at for your proposed development?",
"Do you think the MTR would also contribute to the value of CPS?",
"Why do you think the developers prefer to build smaller flat size?",
"You mentioned the lease term is 99 years less 3 days. So actuallty the lease has expired in 1997. So it is auto renew or what",
"What if the leasee does not agree for such an amount> So the objection lodged to LandsD?",
"Switched to office market. Government office tower in HK is put in tender. About 19-20/s over ground floor shops, built in 1983. It is located in HK. If I'm going to bid this tender, what is your proposal to me? Would you recommend conversion or redevelopment? Or refurbishment? What would be the flat mix? Assuming it is a non- industrial lease.",
"There are many restrictions under the conditions, e.g. NIA AIA. Will they affect the unit rate of your residential units?",
"Will the noise barrier block your residential units?",
"What is the difference between tender result and your valuation",
"Your client ask you to value 2 sites (A and B) next to each other, assume all the conditions are the same. You valued $1 billion. The tender result of Site A is $1.3 billion. Given that the successful bidder of that site may be crazy. How will you valuate site B?",
"How can Site A become a Class B site?",
"Your client is interested to buy several pieces of Agr land in NT and develop to residential, asvise",
"The lot owner of a land with non-offensive trade clause want to do bar and restaurant, advse",
"Your lient has a piece of land in v zone. He wants to build a school there, advise. S.16 for a free-standing school without any other service",
"But the value of land after rezoning to GIC is much lower?",
"Your client has a piece of land with high ecological value, with some natural habitats, extinct species, but he wants to develop it into residential use, would you advise him to destroy all of them and help him submit an application to LandsD?",
"One house+ no absolute height restriction= Fully Profit Lease after completion of building",
"Completion: Breach of SIA in after Breach of height restriction in Before",
"One house: one main entrance, one secondary entrance + MoE"
];
const maxQuestions = questions.length


randNum = maxQuestions => Math.floor(Math.random() * maxQuestions);

function newQuestion() {
    document.getElementById("qOnScreen").innerHTML = questions[randNum(questions.length)]
}
